### ISSUE TITLE
catchtable function

### ISSUE THREAD

**Issue by timearl** [fishfollower/SAM#20]
Is it possible to have a catchtable function included in the package please, analogous to tsbtable?

catchtable <-
function (fit) 
{
    ret <- .tableit(fit, "logCatch", trans = exp)
    return(ret)
}

Thanks for the useful package

**Comment by fishfollower** [comment]
Thanks Tim. I think it is already there: 

https://github.com/fishfollower/SAM/blob/master/stockassessment/R/tables.R#L53-L61
