### ISSUE TITLE
Rename function f and logit_rho

### ISSUE THREAD

**Issue by mebrooks** [fishfollower/SAM#3]
The transformation used on `rho` (the correlation) is not the logit transformation. Also, having a function `f` in a model with a parameter named `f` makes the code confusing.

The function `f` is defined here
https://github.com/fishfollower/SAM/blob/master/stockassessment/src/stockassessment.cpp#L34 

Then it's used to transform `logit_rho` on lines 123 and 132. 
The transformation used here is a special case of the 4-parameter logistic; rename these accordingly.

**Comment by fishfollower** [comment]
Thanks. I think it is corrected now.

**Comment by mebrooks** [comment]
Looks good. Thanks!
