### ISSUE TITLE
Load package to each node

### ISSUE THREAD

**Issue by arni-magnusson** [fishfollower/SAM#40]
Hi!

I need a specific version of the stockassessment package to run my analysis. I have this version installed in a project-specific library called `myproject/library`. Other analyses use other versions of stockassessment. To avoid confusion while working on my project, I do not have the stockassessment package installed globally. I load the correct version using the command
``
library(stockassessment, lib.loc="myproject/library")
``

I already have model.RData containing the fit object, but an error occurs when I run
``
retro(fit, year=4)
``
because it tries to load the wrong version of the stockassessment package, the global version instead of my project-specific package that is already loaded.

The source of the problem seems to be this line of code
https://github.com/fishfollower/SAM/blob/8ebd840/stockassessment/R/run.R#L170
where the `jit` function calls `library(stockassessment)` to load the package to each node.

Do you think it would be possible to implement `jit` without an explicit `library()` call? Currently, it assumes something about the user setup - that only one version of stockassessment is installed - and this assumption may not always hold.

I'll experiment a bit more with this and get back to you.

**Comment by arnima-github** [comment]
To load the correct version of the package to each node, this might be useful:
``
attributes(as.environment("package:stockassessment"))$path
``

It returns the path to the correct (already loaded) version of the package. That looks like a safer approach, to specifically load that:
``
library(stockassessment, lib.loc=attributes(as.environment("package:stockassessment"))$path)
``

**Comment by arnima-github** [comment]
Same but shorter:
``
library(stockassessment, lib.loc=path.package("stockassessment"))
``

**Comment by arnima-github** [comment]
Needs to be the directory containing stockassessment:
``
dirname(path.package("stockassessment"))
``

**Comment by fishfollower** [comment]
Thank you. Hopefully fixed everywhere now (4424bc10f2a7f965e)

**Comment by arni-magnusson** [comment]
Looking good :)
