### ISSUE TITLE
nscod test

### ISSUE THREAD

**Issue by mebrooks** [fishfollower/SAM#6]
It seems that there might be a bug in the nscod example. When I run `make` in that directory, I get this

```
Error in scan(filen, skip = 2, n = 5, quiet = TRUE) : 
  scan() expected 'a real', got 'IBTS_Q1_gam'
Calls: source -> withVisible -> eval -> eval -> read.ices -> scan
Execution halted
make: *** [all] Error 1
```
I didn't look into the details.

**Comment by fishfollower** [comment]
That should have been fixed. Try to do 

make

and then 

make test

**Comment by fishfollower** [comment]
updated Makefile to make sure make install was run before make test

**Comment by mebrooks** [comment]
Yep, that fixed it. 

I'm still trying to figure out what Travis is doing. It didn't catch that error.

**Comment by fishfollower** [comment]
I guess the error was not there for travis to see. The only reason you got the error was because it was testing an older version of stockassessment on your system

**Comment by mebrooks** [comment]
Ok, that's interesting. In that case, I think I'll make a test with a small error on the `travis` branch to be sure that Travis catches it.
