### ISSUE TITLE
installation issue with Windows 32-bit

### ISSUE THREAD

**Issue by marchtaylor** [fishfollower/SAM#61]
I'm having a problem updating my package:

```
cc1plus.exe: out of memory allocating 538160 bytes
make: *** [C:/Users/taylor/DOCUME~1/R/R-36~1.3/etc/i386/Makeconf:215: stockassessment.o] Error 1
ERROR: compilation failed for package 'stockassessment'
* removing 'C:/Users/taylor/Documents/R/win-library/3.6/stockassessment'
```

The solution is to only install within the R 64-bit version:
`devtools::install_github("fishfollower/SAM/stockassessment", INSTALL_opts=c("--no-multiarch"))`

Maybe something add to the readme.

**Comment by fishfollower** [comment]
Added. Thanks
