### ISSUE TITLE
.plotit public

### ISSUE THREAD

**Issue by mebrooks** [fishfollower/SAM#8]
Would it make sense for the .plotit funciton to be public so that users can see the arguments (e.g. add, ci, cicol)? Alternatively, we may want to document these arguments for each of the other functions they can be used with (e.g. ssbplot)

**Comment by mebrooks** [comment]
It seems that there are problems when passing these extra arguments to the multiple-plot functions (see example below), so I think I'll just document them with the functions where they work.

In this example, all the plots in the 2nd command get added to the recruitment plot. 
```
plot(fit, ci=FALSE)
plot(fit, add=TRUE, cicol="red")
```
I don't want to get into the details of these plotting functions. I just wanted to document the features that I found helpful while writing a vignette.

**Comment by fishfollower** [comment]
Need to look at that more. OK to make .plotit public, but with a different name.

**Comment by fishfollower** [comment]
Hi Mollie,

Added the add=T problem to the doc for plot.sam
